sudo: false

language: php

php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer self-update
  - composer install

script: 
  - bin/phpcs
  - bin/phpspec --config phpspec.travis.yml

after_script:
  - bin/coveralls -v
