sudo: false

language: php

php:
  - 5.5
  - 5.6
  - 7.0

cache:
  directories:
    - vendor
    - bin

before_script:
  - composer self-update
  - composer install
  - mkdir build/

script: 
  - bin/phpcs
  - bin/phpspec run --config phpspec.travis.yml

after_script:
  - bin/coveralls -v
